### ISSUE TITLE
How can i revoke snap token?

### ISSUE THREAD

**Issue by RizkyArifNur** [Midtrans/midtrans-nodejs-client#11]
Can i revoke snap token that generated from ```createTransaction()``` method?

**Comment by rizdaprasetya** [comment]
Hi @RizkyArifNur  there's no official `revoke` API method.
However there's some work around: 
- if you know how long you will need an Snap token to active, you can set via `expiry` JSON parameter. Or
- do another `createTransaction()` with **same order ID** to obtain another token, it will revoke the old token, only the latest 1 should active.

Thanks
