### ISSUE TITLE
Missing "Direct Refund" feature

### ISSUE THREAD

**Issue by fachrihawari** [Midtrans/midtrans-nodejs-client#13]
Halo developers 👋 
Thanks for your awesome sdk.
But currently I need a direct refund feature and I can't find any function for `direct refund` like on this [link](https://api-docs.midtrans.com/#direct-refund-transaction).

Are you have any plan to add this feature on the sdk ?

**Comment by rizdaprasetya** [comment]
Yes we are planning to add that new refund endpoint. Will be updated soon around 1-2 week, once we are available. Thanks for reaching us!

**Comment by fachrihawari** [comment]
@rizdaprasetya Thanks for the response ⚡️

**Comment by rizdaprasetya** [comment]
@fachrihawari should be added now, current version `midtrans-client@1.1.0`

**Comment by fachri-adakerja** [comment]
Thanks @rizdaprasetya 🚀
