### ISSUE TITLE
What is the different using CoreAPI to get transaction response, or use transaction respon directly from req.body that send by Midtrans HTTP Post Notification?

### ISSUE THREAD

**Issue by RakaDoank** [Midtrans/midtrans-nodejs-client#15]
I've seen this example how to handle the transaction status
https://github.com/Midtrans/midtrans-nodejs-client/blob/master/examples/expressApp/app.js#L87

But what if i just use the `req.body` to handle transaction status directly, instead of 
`core.transaction.status(req.body.transaction_id).then(transactionObject)` to get transaction status and handle it from that.

Aren't they basically same data?
Is it has "secure" thing purposes using CoreAPI rather than the req.body itself?

Example, i can get the transaction_id directly from `req.body.transaction_id` instead of `transactionObject.transaction_id`

**Comment by rizdaprasetya** [comment]
Hi @RakaDoank good question, it is explained in detail here:
https://beta-docs.midtrans.com/en/after-payment/http-notification?id=verify-notification-authenticity

Summary: it is to ensure the notification you receive is securely coming from Midtrans, especially if some outsider somehow figure-out/know your notification (although will not be easy), that outsider can send fake transaction status.

To solve that kind insecure factor, you can use `.status()` function, OR alternatively check the `signature_key` attribute. Which explained on the link above.

`.status()` call also to ensure you get the most recent/updated notification.

**Comment by rizdaprasetya** [comment]
Closed due to inactivity, if issue persist please reply.
