### ISSUE TITLE
Add option to override header request

### ISSUE THREAD

**Issue by aquaswim** [Midtrans/midtrans-nodejs-client#17]
according to [this documentation](https://snap-docs.midtrans.com/#override-notification-url) we can change notification url by adding header `X-Override-Notification` but with this library there is no way we can do this.

**Comment by rizdaprasetya** [comment]
Yes, we are planning to add that new capability to set HTTP headers soon.

**Comment by rizdaprasetya** [comment]
For now it can overriding HTTP header can be achieved via the following way:
https://github.com/Midtrans/midtrans-nodejs-client#override-http-notification-url

**Comment by rizdaprasetya** [comment]
Sorry there were [some mistake on the example, fixed now](https://github.com/Midtrans/midtrans-nodejs-client/pull/21/commits/eba9101c622126c1ab7172d301b5270666d6b55b).
