### ISSUE TITLE
Cors

### ISSUE THREAD

**Issue by alfianpurnomo-elev** [Midtrans/midtrans-nodejs-client#26]
Saya sedang mengintegraskan dengan menggunakan CoreAPI dan next js
tapi kenapa selalu kena cors ya?

**Comment by rizdaprasetya** [comment]
Hi @alfianpurnomo-elev berikut jawabannya di [integration FAQ kami](https://docs.midtrans.com/en/other/faq/technical?id=when-i-try-to-send-request-to-midtrans-api-it-always-gets-blocked-by-cors-policy-on-the-browser-what-is-the-issue)

Semua request yg membutuhkan `serverKey` sebagai credentials sebaiknya dilakukan via Backend bukan Frontend. 
Package ini juga ditujukan untuk backend NodeJS bukan untuk frontend JS.

Thanks. Untuk jawaban lebih cepat silahkan hubungi email support@midtrans.com

**Comment by alfianpurnomo-elev** [comment]
Saya menggunakan next js
Dan hit API coreAPI untuk get token cartu credit menggunakan standar ajax request
Apakan memang itu di block by cors apa gimana?
Kalo saya pake html biasa bisa dan embet script di header bisa
Kalo di next js gak bisa embet script itu
Ada solusi?

**Comment by rizdaprasetya** [comment]
Hi @alfianpurnomo-elev 
Standard Ajax tidak bisa, harus menggunakan metode Ajax JSONP agar tidak diblock CORS dari browsernya.

React/Next JS tetap bisa embedd script jika paham cara kerja frameworknya, contohnya [berikut ini ada developer yang bisa](https://github.com/Midtrans/midtrans-nodejs-client/issues/25#issue-804159793), di sample codenya menggunakan:
```
  useEffect(() => {
    if (typeof window !== "undefined") {
      const myScript = document.createElement("script");
      myScript.setAttribute(
        "src",
        "https://app.sandbox.midtrans.com/snap/snap.js"
      );
      myScript.setAttribute(
        "data-client-key",
        "SB-Mid-client-XXX"
      );
      document.head.appendChild(myScript);
    }
  }, []);
```

Atau coba cara [berikut ini untuk embedd script di React](https://docs.midtrans.com/en/other/faq/technical?id=my-developer-uses-react-js-frontend-framework-and-is-unable-to-use-midtransminjssnapjs-what-should-i-do)

Thanks
