### ISSUE TITLE
Bisa untuk react-native?

### ISSUE THREAD

**Issue by mosleim** [Midtrans/midtrans-nodejs-client#3]
selamat malam, library ini bisa untuk react-native?

**Comment by rizdaprasetya** [comment]
Hi @mosleim 
Lib ini officially dibuat untuk server side Node JS, dan belum pernah ditest untuk React Native.
Tidak ada jaminan akan bisa digunakan di platform selain server side Node JS.

Lib ini memanfaatkan `Axios` sebagai HTTP library, kalau berdasarkan doc berikut:
https://facebook.github.io/react-native/docs/network.html#using-other-networking-libraries
di React Native Axios bisa digunakan, jadi silahkan dicoba, ada kemungkinan lib ini pun bisa digunakan.

Kalau pun bisa, ada security concern yg harus Anda pikirkan, `server key` akun Midtrans Anda, yg dibutuhkan untuk menggunakan library ini, jadi ter-expose pada code App React Native Anda. Sedangkan code App React Native bisa dengan mudah di lihat sourcenya oleh user yg mendownload App anda.

Sebaiknya gunakan lib ini pada backend / server-side saja, gunakan App React Native anda sebagai hanya sebagai consumer.

**Comment by mosleim** [comment]
ok, sepertinya saya melakukan kekeliruan. rupanya library ini untuk server-side(sesuai penjelasan @rizdaprasetya ). sedangkan saya mengira library ini adalah library untuk client side di sistem saya.

**Comment by kikikiswanto** [comment]
> ok, sepertinya saya melakukan kekeliruan. rupanya library ini untuk server-side(sesuai penjelasan @rizdaprasetya ). sedangkan saya mengira library ini adalah library untuk client side di sistem saya. terimakasih.

sudah dapat solusi kah untuk react native ?
