### ISSUE TITLE
notificationJson Error not found

### ISSUE THREAD

**Issue by ArifandiHartono** [Midtrans/midtrans-nodejs-client#34]
saat saya menjalankan code midatransSnap.transaction.notification(notificationJson);
saya mendapatkan error
2021-08-19T17:32:49.789Z error: /v1/transaction/payment_status - 127.0.0.1 - ReferenceError: notificationJson is not defined 
apakah bisa dibantu? Terima kasih

**Comment by ArifandiHartono** [comment]
sudah kurang teliti saya harus tambahkan req.body

**Comment by rizdaprasetya** [comment]
Betul. Baiklah jika issue sudah solve. Terima kasih.

Bagi yang lain jika mengalami issue yang sama bisa refer ke example berikut:
https://github.com/Midtrans/midtrans-nodejs-client/blob/fb121c539891246e824447116707945c25b3a2fa/examples/expressApp/app.js#L130-L133
