### ISSUE TITLE
callback pending run twice

### ISSUE THREAD

**Issue by reizhafajrian** [Midtrans/midtrans-nodejs-client#41]
window.snap.pay(post.transaction.redirect_url, {
      onSuccess: async (result) => {
        console.log(result, "result");
      },
      onPending: async (result) => {
        return alert("Pending");
        // return settemp(temp.concat(result));
      },
      onError: async (result) => {
        return alert("Error");
        // return settemp(temp.concat(result));
      },
    });

says membuat website dimana pembayaran menggunakan midtrans semua berjalan baik baik saja sampai callback pending  berjalan dua kali

**Comment by rizdaprasetya** [comment]
Hi @reizhafajrian terima kasih sudah reach out, issue ini valid dan sudah di acknowledge tim kami, akan butuh dicek & fix oleh internal tim kami lebih lanjut. Akan kami infokan jika sudah difix. Untuk sekarang mohon di ignore saja callback ke 2 nya, seharusnya hanya trigger 1x callback saja. Thanks!

Note: issue hanya terjadi di sandbox env, production env berjalan baik.

**Comment by rizdaprasetya** [comment]
Hi @reizhafajrian tim kami confirm fixnya sudah dilakukan di tanggal 11 Januari. Silahkan dicoba kembali dan infokan jika masih terkendala ya. Thanks!
