### ISSUE TITLE
Type for Typescript

### ISSUE THREAD

**Issue by zaen-lab** [Midtrans/midtrans-nodejs-client#42]
I'm using TypeScript and don't see any type from your library.
And it bothers me a lot.

I create my own using this command
`tsc ./node_modules/midtrans-client/index.js ./node_modules/midtrans-client/lib/*.js --declaration --allowjs --emitDeclarationOnly --outFile @types/midtrans.d.ts`

I thing you can provide better one with creating npm package @types/midtrans-client.
You are a big company. and it's a shame if you can't give something like that (at least for me).

**Comment by Andrenzo17** [comment]
Hi @zaen-lab thank you for your suggestion.

We have Community contribution in Typescript please check this link https://github.com/restuwahyu13/midtrans-node
We all ready put the link in our docs Library & plugins too https://docs.midtrans.com/en/technical-reference/library-plugin

Thank you
