### ISSUE TITLE
Hapus bagian BACK TO MERCHANTS WEB

### ISSUE THREAD

**Issue by bobwatcherx** [Midtrans/midtrans-nodejs-client#50]
![Screenshot_2022-11-29-11-29-14-93](https://user-images.githubusercontent.com/52072811/204483649-27f1f9d5-5de2-4a19-8404-3e996ce74e02.png)

bagaimana cara menghapus bagian 
BACK TO MERCHANTS WEB pada gambari di atas
Dan menghapus fungsi redirecting

Saya ingin polos aja . Ga ada redirect redirect
Kalo bisa . Di bagian mana yg harus saya edit 

Terima kasih

**Comment by Andrenzo17** [comment]
Hi @bobwatcherx 

Untuk implementasi diatas menggunakan SNAP Redirect ya?
untuk Back to merchant web tidak bisa dihilangkan ya.
Namun jika ingin fungsi redirect dihapus pada halaman ini https://dashboard.sandbox.midtrans.com/settings/vtweb_configuration untuk **Finish Redirect URL*** silakan di kosongkan.

Nantinya ketika redirect url kosong maka ketika selesai pembayaran akan tampil halaman seperti dibawah ini
<img width="426" alt="Screen Shot 2022-11-29 at 16 32 38" src="https://user-images.githubusercontent.com/83454487/204492194-37f3ee72-c194-4bc9-8ca0-703ac7afd3df.png">
Terima kasih

**Comment by bobwatcherx** [comment]
Udah saya hapus . Finish redirect url tapi
Masih sama aja

![Screenshot_2022-11-29-17-56-48-14](https://user-images.githubusercontent.com/52072811/204511798-d070b2b1-1da2-49a2-bf15-fce51c46d450.png)
![16697195267937240127052700683155](https://user-images.githubusercontent.com/52072811/204512005-fdfdc412-7b70-4086-8b5a-bf9b22e5d9b0.jpg)
