### ISSUE TITLE
Bagaimana cara melakukan callback midtrans setelah melakukan pembayaran.

### ISSUE THREAD

**Issue by Adhri14** [Midtrans/midtrans-nodejs-client#56]
Halo mas @rizdaprasetya maaf mas, saya ingin bertanya. saya di sini kesulitan terkait melakukan callback midtrans setelah user melakukan pembayaran yang dimana saya harus mengupdate status transaksi saya dengan mengecek apakah fraud status nya ini accept, failure dll. Di sini lebih tepat nya saya harus menggunakan method yang mana dan mohon maaf mas bisa berikan contoh implementasinya agar saya bisa lebih mengerti cara penggunaan nya mas. Terima kasih :)

**Comment by Andrenzo17** [comment]
Hi Mas @Adhri14 berikut docs lengkap untuk handle notification https://docs.midtrans.com/docs/handle-after-payment dan ini example handling notificationya ya https://docs.midtrans.com/docs/https-notification-webhooks#example-on-handling-http-notifications

Terima kasih

**Comment by Adhri14** [comment]
Terima kasih banyak mas @Andrenzo17 saya akan coba implementasi code yang mas berikan.
