### ISSUE TITLE
"No MID/TID for this transaction"

### ISSUE THREAD

**Issue by ilhamkukuh** [Midtrans/midtrans-nodejs-client#57]
Halo, saya mendapatkan error "Credit card token is no longer available. Please create a new one." ketika implementasi card payment. untuk token sendiri aku dapatkan dari response success midtrans-new-3ds. bagaimana mengatasinya? 

env = production

**Comment by Andrenzo17** [comment]
Hi @ilhamkukuh , 

jadi issuenya tokennya sudah tidak available atau ketika charge mendapatkan No MID/TID for this transaction?
Untuk issue ini kami membutuhkan beberapa data merchant dan bersifat confidential. 
Sehingga kami arahkan untuk contact kami melalui link berikut ya https://midtrans.com/contact-us dengan menyertakan sample order id, request dan response error yang didapat agar bisa di cek lebih lanjut.

Terima kasih
