### ISSUE TITLE
Support for ejs import

### ISSUE THREAD

**Issue by RobyCigar** [Midtrans/midtrans-nodejs-client#58]
Hi, thanks for the library, currently i have problem with the import statement
how can I import the package using ejs syntax in my client?
`import snap from 'midtrans-client'`
currently the available docs only explain about common js import
`const blah = require('midtrans-client')`
thank you

**Comment by Andrenzo17** [comment]
Hi @RobyCigar do you mean this is for client side is front end?
This library/package is mainly NOT FOR FRONTEND (Browser's javascript) usage, but for backend (Node JS server) usage:

- This is mainly for backend usage, to do secure server-to-server/backend-to-backend API call.
- You may/will encounter CORS issue if you are using this to do API request from frontend.
- Your API ServerKey may also be exposed to public if you are using this on frontend.
- If what you need is to display Snap payment page on your frontend, please [follow this official documentation](https://docs.midtrans.com/en/snap/integration-guide?id=_2-displaying-snap-payment-page-on-frontend)

Thank you

**Comment by RobyCigar** [comment]
thanks for your reply @Andrenzo17 
sorry I thought the word client in "midtrans-nodejs-client" mean its for the client(frontend)

Initially i was looking for snap npm package, the docs said i should add inline script in my html, but i feel like its not a "good" way to add package directly using inline script in my project, i would rather using npm than inline script, so i stumbled to this repo
