### ISSUE TITLE
IRIS API Access denied

### ISSUE THREAD

**Issue by adityazxzxz** [Midtrans/midtrans-nodejs-client#60]
halo, saya mendapatkan response HTTP status code: 401. HTTP Basic: Access denied untuk API IRIS getBeneficiaryBanks tetapi saat menggunakan API Core maupun Snap berjalan dengan normal. Apakah ada config yang kurang?

**Comment by Andrenzo17** [comment]
Hi @adityazxzxz , 

Jika mendapatkan status code 401 berarti key yang digunakan masih belum sesuai. Apakah Environment nya menggunakan Production atau Sandbox? pastikan menggunakan IRIS key dengan Environment yang sesuai ya.

Bisa refer ke docs berikut https://docs.midtrans.com/reference/https-request#api-base-url dan https://docs.midtrans.com/reference/https-request#api-base-url

Jika masih berkendala apakah bisa mengirimkan sample curl dan error response lengkap kepada kami? karena membutuhkan data pribadi maka saya arahkan menghubungi melalui email ya https://midtrans.com/contact-us/irispayouts-service-information

Terima kasih
