### ISSUE TITLE
midtrans register API

### ISSUE THREAD

**Issue by ayamgoreng47** [Midtrans/midtrans-nodejs-client#61]
Hello Pak Rizda, izin bertanya apakah midtrans memungkingkan registrasi user melalui API kedepannya, pak? Terima kasih.

**Comment by Andrenzo17** [comment]
HI @ayamgoreng47 apakah bisa tolong jelaskan lebih detail maksud dari registrasi user itu seperti apa? serta tujuan register user untuk call API midtrans yang mana?

Oh ya jika pertanyaan general dan tidak berhubungan dengan repo ini, agar mendapatkan response lebih cepat bisa menghubungi kami melalui channel contact us berikut ya https://midtrans.com/contact-us
Terima kasih
