### ISSUE TITLE
Cara melanjutkan transaksi

### ISSUE THREAD

**Issue by welsonoktario** [Midtrans/midtrans-nodejs-client#62]
Hi, saya ingin bertanya apakah ada cara, referensi, atau dokumentasi untuk melanjutkan transaksi yang telah terbuat sebelumnya? Saya mendapatkan kesulitan mencari permasalahan yang saya cari, baik di website dokumentasi resmi, google, dan lainnya. Terima kasih.

**Comment by Andrenzo17** [comment]
Hi @welsonoktario apakah bisa tolong dijelaskan lebih lanjut maksud dari melanjutkan transaksi? Apakah yang di maksud adalah mengedit order id yang telah terlanjut dibuat atau bagaimana? apakah menggunakan produk SNAP atau CORE API?

jika pertanyaan general dan tidak berhubungan dengan repo ini, agar mendapatkan response lebih cepat bisa menghubungi kami melalui channel contact us berikut ya https://midtrans.com/contact-us
Terima kasih

**Comment by welsonoktario** [comment]
Hi, terima kasih atas balasannya, jadi pertanyaan saya sebelumnya untuk melanjutkan pembayaran pada transaksi yang sebelumnya telah terbuat, namun belum terbayarkan.

Sekarang, masalah sudah ter-solved, dengan cara memanggil `snap.pay(<snap_token>)`, dimana `snap_token` didapatkan dari proses pembuatan invoice sebelumnya. Maka dari itu, saya akan menutup issue ini. Terima kasih.
