### ISSUE TITLE
[node v20.17.0 express js] Snap - CANNOT FIND MODULE 

### ISSUE THREAD

**Issue by sasakiRoo** [Midtrans/midtrans-nodejs-client#76]
saya baru pertama kali menggunakan midtrans, dan saya menggunakan node js express untuk mencobanya dengan memodifikasi kode dari dokumentasi resmi midtrans: https://docs.midtrans.com/docs/snap-snap-integration-guide. Namun, saya mendapati error: 
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module './SnapBiApiRequestor'
Require stack:

**Comment by ismailjamiljauhari** [comment]
sama error kaya gitu juga @sasakiRoo

**Comment by ismailjamiljauhari** [comment]
![Screen Shot 2024-10-21 at 18 34 07](https://github.com/user-attachments/assets/83d56e07-8a95-4b5e-b3ba-374937157646)

**Comment by sasakiRoo** [comment]
iyaa itu bang buat aku bingung. apa harus install module itu apa gimana? padahal aku udah berkali-kali install-uninstall midtrans-client.

```
const midtransClient = require('midtrans-client')
const midtransClient = require('midtrans-client').Midtrans;
```
pas kedua baris itu di-disabled, semua berfungsi seperti semula.

**Comment by sasakiRoo** [comment]
fixed, theres type in module snapBi
[https://github.com/Midtrans/midtrans-nodejs-client/blob/master/lib/SnapBi/snapBi.js](url)

**Comment by uziwuzzy** [comment]
bole di share lebih detail issuenya dmn ya? library versi berapa?

**Comment by ismailjamiljauhari** [comment]
@uziwuzzy  version: 1.4.1

**Comment by sasakiRoo** [comment]
Because of i use this 1.4.1 version, when i push this to netlify, i got the same error. So, i created a pull request to fix the typo. I hope it will be approved.

Dear Midtrans, Please see or consider this, so you don't lose a customer from node-js side.

**Comment by uziwuzzy** [comment]
sorry for the error, please downgrade to use v 13* for now. will fix the release nextweek.
