### ISSUE TITLE
Bug after install npm i midtrans-client on ubuntu 20.04 MODULE NOT FOUND

### ISSUE THREAD

**Issue by Rizal-R** [Midtrans/midtrans-nodejs-client#81]
![error](https://github.com/user-attachments/assets/17f7dc3e-3d00-418d-ae79-02d56c9316bf)

**Comment by robertyulisman** [comment]
![image](https://github.com/user-attachments/assets/492eb02d-a187-43e5-86e0-a40e9e5d9821)
sama, apakah ada perubahan ? sudah makai library terbaru, juga masih sama errornya

**Comment by Rizal-R** [comment]
versi 1.3.0 - 1.4.1 masi sama error module not found

**Comment by robertyulisman** [comment]
> versi 1.3.0 - 1.4.1 masi sama error module not found

mana nih, blm ada balasan sama owner nya, mana sistem udah 2 hari gk bisa dipake, gara2 error ini

**Comment by uziwuzzy** [comment]
sorry for the error, please use other version except v1.4*, you can downgrade to use v1.3* for now https://www.npmjs.com/package/midtrans-client?activeTab=versions. Will fix the release within this week.

Dibawah versi 1.4 itu harusnya bisa karena belum ada SnapBi, coba di hapus cachenya.

**Comment by robertyulisman** [comment]
> sorry for the error, please use other version except v1.4*, you can downgrade to use v1.3* for now https://www.npmjs.com/package/midtrans-client?activeTab=versions. Will fix the release within this week.
> 
> Dibawah versi 1.4 itu harusnya bisa karena belum ada SnapBi, coba di hapus cachenya.

baik, terima kasih bg, saya coba dulu, dan nanti kasih feedback, apakah solved atau tidak

**Comment by robertyulisman** [comment]
> sorry for the error, please use other version except v1.4*, you can downgrade to use v1.3* for now https://www.npmjs.com/package/midtrans-client?activeTab=versions. Will fix the release within this week.
> 
> Dibawah versi 1.4 itu harusnya bisa karena belum ada SnapBi, coba di hapus cachenya.

![image](https://github.com/user-attachments/assets/f539dd8d-c1a1-4bf1-9d24-bdb643672a3b)
masih sama, udah clear cache dan downgrade ke versi 1.3.1

**Comment by uziwuzzy** [comment]
kalau masih ada snapBi files, berarti masih di versi 1.4*, coba di make sure lagi, bisa dgn step ini.

// Delete everything

```
rm -rf node_modules
rm package-lock.json
```

// Clear all caches
```
npm cache clean --force
npm cache verify
```

// Reinstall everything fresh
```npm install```

**Comment by robertyulisman** [comment]
> kalau masih ada snapBi files, berarti masih di versi 1.4*, coba di make sure lagi, bisa dgn step ini.
> 
> // Delete everything
> 
> ```
> rm -rf node_modules
> rm package-lock.json
> ```
> 
> // Clear all caches
> 
> ```
> npm cache clean --force
> npm cache verify
> ```
> 
> // Reinstall everything fresh `npm install`

sudah semua versi saya coba dari 1.2.3 sampai terbaru, udah test di localhost sampai ke ubuntu semua tidak ada yg berhasil 
sudah saya coba dari versi 1.2.3, 1.2.4, 1.3.0, 1.3.1 dan sudah hapus node module, clear chache dan sudah paling bersih, tp tidak ada yg berhasil, coba dari sisi kamu di test juga yg versi 1.3.* kebawah apakah berhasil atau seperti apa ? 

`
TypeError: midtransClient.Snap is not a constructor
    at Object.<anonymous> (E:\1.kerjaan\1. Proo\new\prooApp\backend\routes\api\midtran.js:25:14)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
`

**Comment by Rizal-R** [comment]
fixed downgrade version to 1.3.1
