### ISSUE TITLE
Custom fields on snap api?

### ISSUE THREAD

**Issue by chrisandoryan** [Midtrans/midtrans-nodejs-client#9]
It is possible to add custom field in snap API? My goal is to attach additional data (e.g customer_id) on HTTP notification webhook. 

I found this on api docs:

Set Custom Fields is a feature that enables merchants to charge a transaction with a unique data according to the merchant's need. Midtrans provides merchants with 3 custom fields that can be used for various utilities. 

It seems I could not find my way there using snap API. 

I've already added the desired field label name from general settings in my merchant admin portal, and send it upon createTransaction() call (alongside the required data such as transaction_details, payment_type, etc). But everytime I received the HTTP notification POST data, I can't find my custom field data.

Thank you in advance.

**Comment by rizdaprasetya** [comment]
Hi @chrisandoryan Yes Snap support it,
Sample request:
```
{
  "transaction_details": {
    "order_id": "123123",
    "gross_amount": 10000
  },
  "credit_card": {
    "secure": true
  },
  "custom_field1": "data",
  "custom_field2": "data",
  "custom_field3": "data"
}
```
do not change the `custom_field1`, the "key" have to be `custom_field1`, you can only change the value of it.
https://snap-docs.midtrans.com/#request-body-json-parameter

For faster response it's recommended to contact our support via email support[at]midtrans.com

**Comment by chrisandoryan** [comment]
Ah I see, this resolve it. Thank you very much!
